set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports H]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports V]
set_property PACKAGE_PIN Y9 [get_ports clock]
set_property PACKAGE_PIN AA11 [get_ports R]
set_property PACKAGE_PIN AB11 [get_ports G]
set_property PACKAGE_PIN AA7 [get_ports B]
set_property PACKAGE_PIN Y5 [get_ports V]
set_property PACKAGE_PIN W5 [get_ports H]

set_property DRIVE 16 [get_ports H]
set_property DRIVE 16 [get_ports V]
set_property SLEW FAST [get_ports H]
set_property SLEW FAST [get_ports V]

set_property PACKAGE_PIN F22 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]


set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN R18 [get_ports btn_right]
set_property PACKAGE_PIN N15 [get_ports btn_left]
set_property IOSTANDARD LVCMOS33 [get_ports btn_left]
set_property IOSTANDARD LVCMOS33 [get_ports btn_right]
set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property PACKAGE_PIN U21 [get_ports {led[3]}]
set_property PACKAGE_PIN V22 [get_ports {led[4]}]
set_property PACKAGE_PIN W22 [get_ports {led[5]}]
set_property PACKAGE_PIN U19 [get_ports {led[6]}]
set_property PACKAGE_PIN U14 [get_ports {led[7]}]


set_property OFFCHIP_TERM NONE [get_ports B]
set_property OFFCHIP_TERM NONE [get_ports G]
set_property OFFCHIP_TERM NONE [get_ports H]
set_property OFFCHIP_TERM NONE [get_ports R]
set_property OFFCHIP_TERM NONE [get_ports V]
set_property SLEW FAST [get_ports {led[7]}]
set_property SLEW FAST [get_ports {led[6]}]
set_property SLEW FAST [get_ports {led[5]}]
set_property SLEW FAST [get_ports {led[4]}]
set_property SLEW FAST [get_ports {led[3]}]
set_property SLEW FAST [get_ports {led[2]}]
set_property SLEW FAST [get_ports {led[1]}]
set_property SLEW FAST [get_ports {led[0]}]
set_property DRIVE 16 [get_ports {led[7]}]
set_property DRIVE 16 [get_ports {led[6]}]
set_property DRIVE 16 [get_ports {led[5]}]
set_property DRIVE 16 [get_ports {led[4]}]
set_property DRIVE 16 [get_ports {led[3]}]
set_property DRIVE 16 [get_ports {led[2]}]
set_property DRIVE 16 [get_ports {led[1]}]
set_property DRIVE 16 [get_ports {led[0]}]
